baseURL = "https://hamit.me/"
languageCode = "tr-TR"
title = "Güvenlik Araştırmacısı"
theme = "maverick"

disableHugoGeneratorInject = true

[menus]
  [[menus.main]]
    name = "Anasayfa"
    pageRef = "/"
    weight = 10

  [[menus.main]]
    name = "Yazılar"
    pageRef = "/posts/"
    weight = 20

[markup]
  [markup.goldmark.renderer]
    unsafe = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    style = "monokailight"

